namespace HesabfaAPISampleCode.Models.Enumarations
{
    public enum AccountType
    {
        General = 0,
        Cash = 1,
        PettyCash = 2,
        Bank = 3,
        AccountsReceivable = 4,
        NotesReceivable = 5,
        ChecksInCollection = 6,
        Inventory = 7,
        PurchaseVAT = 8,
        AccountsPayable = 9,
        NotesPayable = 10,
        SalesVAT = 11,
        IncomeTax = 12,
        SavedIncomeTax = 40,
        OpeningCapital = 13,
        CapitalAdjustment = 14,
        LegalReserve = 15,
        Withdrawals = 16,
        ProfitAndLoss = 17,
        RetainedEarnings = 18,
        Purchase = 19,
        PurchaseReturns = 20,
        PurchaseDiscounts = 21,
        Sales = 22,
        SalesReturns = 23,
        SalesDiscounts = 24,
        ServiceRevenue = 25,
        ServicePurchaseRevenue = 26,
        InventoryAdjustmentIncome = 27,
        FreightRevenue = 28,
        ServiceReturns = 29,
        ServicePurchase = 30,
        FreightExpense = 31,
        InventoryAdjustmentExpense = 32,
        BankFees = 33,
        InventoryAdjustment = 34,
        IncomeSummary = 35,
        ExchangeGain = 36,
        ExchangeLoss = 37,
        InterestRevenue = 38
    }
}
